[[notes]]
timing = 106
lane = "LaneD"

[[notes]]
timing = 716
lane = "LaneJ"

[[notes]]
timing = 721
lane = "LaneK"

[[notes]]
timing = 729
lane = "LaneL"

[[notes]]
timing = 754
lane = "LaneJ"

[[notes]]
timing = 768
lane = "LaneK"

[[notes]]
timing = 782
lane = "LaneL"

[[notes]]
timing = 814
lane = "LaneJ"

[[notes]]
timing = 820
lane = "LaneK"

[[notes]]
timing = 827
lane = "LaneL"

[[notes]]
timing = 836
lane = "LaneSemicolon"

[[notes]]
timing = 850
lane = "LaneJ"

[[notes]]
timing = 859
lane = "LaneK"

[[notes]]
timing = 870
lane = "LaneJ"

[[notes]]
timing = 884
lane = "LaneL"

[[notes]]
timing = 909
lane = "LaneJ"

[[notes]]
timing = 915
lane = "LaneK"

[[notes]]
timing = 920
lane = "LaneL"

[[notes]]
timing = 930
lane = "LaneK"

[[notes]]
timing = 943
lane = "LaneJ"

[[notes]]
timing = 953
lane = "LaneK"

[[notes]]
timing = 959
lane = "LaneL"

[[notes]]
timing = 983
lane = "LaneJ"

[[notes]]
timing = 988
lane = "LaneK"

[[notes]]
timing = 1000
lane = "LaneL"

[[notes]]
timing = 1012
lane = "LaneSemicolon"

[[notes]]
timing = 1024
lane = "LaneJ"

[[notes]]
timing = 1035
lane = "LaneK"

[[notes]]
timing = 1049
lane = "LaneL"

[[notes]]
timing = 1056
lane = "LaneJ"

[[notes]]
timing = 1176
lane = "LaneS"

[[notes]]
timing = 1181
lane = "LaneA"

[[notes]]
timing = 1241
lane = "LaneD"

[[notes]]
timing = 1269
lane = "LaneD"

[[notes]]
timing = 1363
lane = "LaneL"
